// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Musica.Infra.DataBase;

#nullable disable

namespace Musica.Infra.Migrations
{
    [DbContext(typeof(BandaDbContext))]
    [Migration("20221010023051_CreatedFirst")]
    partial class CreatedFirst
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Musica.Domain.Models.BandaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("NomeMusica")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("NOME_MUSICA");

                    b.Property<int>("SequenciaMusica")
                        .HasColumnType("int")
                        .HasColumnName("SEQUENCIA_MUSICA");

                    b.HasKey("Id");

                    b.ToTable("MUSICAS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
